### ISSUE TITLE
Error when running storybook storybook in dev or build with node 17

### ISSUE THREAD

**Issue by elhaw** [m3ntorship/m3ntorship-ui#11]
**Story**
when I run storybook with node 17  it shows the below error 
OS :Windows 10 Enterprise
```
10% building 1/7 modules 6 active /workspaces/m3ntorship-ui/node_modules/@storybook/addon-outline/preview.js-generated-config-entry.jsnode:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:135:10)
    at module.exports (/workspaces/m3ntorship-ui/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/workspaces/m3ntorship-ui/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/workspaces/m3ntorship-ui/node_modules/webpack/lib/NormalModule.js:471:10)
    at /workspaces/m3ntorship-ui/node_modules/webpack/lib/NormalModule.js:503:5
    at /workspaces/m3ntorship-ui/node_modules/webpack/lib/NormalModule.js:358:12
    at /workspaces/m3ntorship-ui/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/workspaces/m3ntorship-ui/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at /workspaces/m3ntorship-ui/node_modules/loader-runner/lib/LoaderRunner.js:205:4
    at /workspaces/m3ntorship-ui/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.9.1
```
**Tasks**
we need to address which node version we will use in the project 
we need to sure the project works fine with node version we will use
we need to check it on different OS( mac & Linux) 

**Helpful resources **
I do not know  exactly why but the issue here [storybook](https://github.com/storybookjs/storybook/issues/16555)

## It works fine with nodejs 14,15,16,18

**Comment by elhaw** [comment]
we use nodejs  14.x in the project and the issue is resolved.
